version: '6.7'
services:
  webfm-postgresql:
    image: postgres:15
    container_name: webfm-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data